<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DotNetScaffold.Abstractions\DotNetScaffold.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.29" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
